DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS
(
    ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255)
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES
(
    ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255)
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS
(
    ID        BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE     VARCHAR(255),
    AUTHOR_ID INT,
    GENRE_ID  INT,
    CONSTRAINT FK_AUTHORS FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_GENRES FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID) ON DELETE CASCADE
);